export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export SYSTEMD_EDITOR='/usr/bin/micro'
export DIFFPROG='/usr/bin/micro'
export EDITOR='/usr/bin/micro'
export VISUAL='/usr/bin/kate -n'
export AMD_VULKAN_ICD=RADV
export XCURSOR_SIZE=30
export BROWSER=firefox
export TERM=alacritty
